name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Notify server about update
      uses: CamiloGarciaLaRotta/watermelon-http-client@v1.5
      with:
        url: 'http://159.69.241.223:3000/deploy'
        method: post
        data: '{ "title": "dummy-todo", "userId": 1, "completed": false }'
