name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Notify server about update
      uses: satak/webrequest-action@master
      with:
        url: 'http://159.69.241.223:3000/deploy'
        method: POST
        payload: '{"name": "Somename"}'
